### ISSUE TITLE
string utils has been moved in newer ember-cli

### ISSUE THREAD

**Issue by themmer** [trabus/ember-cli-mv#7]
I can push a pr if you want, but I don't have access

I am using ember-cli 2.10 and cannot start the server without an error of a missing module

lib/tasks/update-paths.js
-var stringUtils  = require('ember-cli/lib/utilities/string');
+var stringUtils  = require('ember-cli-string-utils');

See this fix as an example:
https://github.com/DockYard/ember-cli-custom-assertions/pull/15/files?diff=unified

**Comment by trabus** [comment]
I've made the fix and pushed a new release, however I would not advise continuing use of this addon, as it has some pretty severe side effects in certain corner cases around the renaming inside templates. I hit a pretty big wall trying to figure it out, and haven't had the time or energy to revisit the project. :\

**Comment by themmer** [comment]
Thanks @trabus for the fast response! I appreciate the effort. It's hard to keep up with those moving targets too.
